"""Init DB

Revision ID: 06b186126593
Revises: 
Create Date: 2023-12-21 10:31:37.929676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b186126593'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('user_session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('transcribe_id', sa.String(), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_session_id')
    )
    op.create_table('session_msg',
    sa.Column('session_msg_id', sa.Integer(), nullable=False),
    sa.Column('user_session_id', sa.String(), nullable=False),
    sa.Column('user_msg_content', sa.String(), nullable=False),
    sa.Column('system_msg_content', sa.String(), nullable=True),
    sa.Column('create_at', sa.Date(), nullable=False),
    sa.Column('feedback', sa.Boolean(), nullable=True),
    sa.Column('feedback_content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_session_id'], ['user_session.user_session_id'], ),
    sa.PrimaryKeyConstraint('session_msg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_msg')
    op.drop_table('user_session')
    # ### end Alembic commands ###
