"""Init database

Revision ID: 2bbf61880066
Revises: 
Create Date: 2024-12-09 18:55:13.626370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bbf61880066'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_msg',
    sa.Column('session_msg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_session_id', sa.Integer(), nullable=False),
    sa.Column('user_msg_content', sa.String(), nullable=False),
    sa.Column('system_msg_content', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('feedback', sa.Boolean(), nullable=True),
    sa.Column('feedback_content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_session_id'], ['user_chat_session.user_session_id'], ),
    sa.PrimaryKeyConstraint('session_msg_id')
    )
    op.drop_table('user')
    op.alter_column('user_chat_session', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_chat_session', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('fk_user_session_user_id', 'user_chat_session', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_user_session_user_id', 'user_chat_session', 'user', ['user_id'], ['user_id'])
    op.alter_column('user_chat_session', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_chat_session', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('token_expire_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_banned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ban_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_pkey'),
    sa.UniqueConstraint('address', name='user_address_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('session_msg')
    # ### end Alembic commands ###
