"""remove trash param

Revision ID: 58544855b2cf
Revises: 7e50bc2dabed
Create Date: 2024-03-04 15:52:15.629965

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '58544855b2cf'
down_revision: Union[str, None] = '7e50bc2dabed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_session', 'transcribe_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
